spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring_db
    username: thienpg
    password: zaQ@1234
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
